name: Publish update

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        with:
          node-version: "16.x"
          cache: "yarn"
          registry-url: "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}"

      - run: yarn install

      - run: yarn publish
        name: Publish to npm
