name: Publish update

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: "18.x"
          cache: "yarn"
          registry-url: "https://registry.npmjs.org/"

      - run: yarn install

      - run: yarn publish
        name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
